"""Add user.patronomic

Revision ID: 7aa9b723e39a
Revises: ad88152a2f54
Create Date: 2024-08-30 10:48:52.991347

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7aa9b723e39a'
down_revision: Union[str, None] = 'b81679b54bc2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('patronomic', sa.VARCHAR(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'patronomic')
    # ### end Alembic commands ###
